### ISSUE TITLE
Lỗi - Nhập viện đối tượng thu phí

### ISSUE THREAD

**Issue by lqbinh1987** [dhhiswork/Loi#98]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Bình**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **18/12/2024**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `84133`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BV Sản Nhi TV**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `binh_sannhitv_loinhapvien_thuphi`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5432`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`NAS/DuLieuCongTy/Database/binh_sannhitv_loinhapvien_thuphi.rar`]
###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2024015607` - _**MaKB**_: `2412003256` - _**MaBA**_: `MaBA` _**NgayKCB**_: `18/12/2024` - _**MaPhong**_: `01` - _**MaDV**_: `10` - _**ThangKT**_: `12` - _**NamKT**_: `2024`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

Lưu nhập viện bị lõi như hình dưới.
Lưu ý lỗi này xuất hiện ở nhiều đơn vị

Phiên bản :2024.12.18.074926AM
System.ArgumentOutOfRangeException: Index and length must refer to a location within the string.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Prescription.Forms.FrmNhapVien.setBNNoiTru()
   at Prescription.Forms.FrmNhapVien.btnClick(Object sender, EventArgs e)

![image](https://github.com/user-attachments/assets/c416c5b2-7e3b-48d9-962f-46b07bfd7f7a)

**Comment by tolaptrinh-issue** [comment]
### <sub>✔️ Tiếp nhận công việc<sup><sup>[HD.05]</sup></sup></sub>
  
  ---
  
  - **📘 Mô tả thực hiện:**
    - [ ] ***Kiểm thử và chỉnh lỗi theo luồng công việc.*** 
  
  - **⏳ Thời gian hoàn thành:** **_2024-12-20_** 
  
  - **🧑‍💻 Thực hiện:** @lequocthong29 
  
  ---
  
  <sup>**📢Lưu ý tiếp nhận:**</sup>
  <sup>🗒 Mô tả cách thức thực hiện, ghi rõ cách xử lý, thay đổi nghiệp vụ để đáp ứng yêu cầu luồng công việc này...</sup>
  <sup>🗒 Trách nhiệm theo dõi đến khi Công việc được xác định hoàn thành (khó khăn, vướng mắc trao đổi với cấp quản lý).</sup>
  <sup>🗒 Ghi nhận thời gian hoàn thành. Định dạng YYYY-MM-DD </sup>
  <sup>🗒 Không tiếp nhận hoặc thời gian vượt quá thời gian trên phải có lý do.</sup>
  <sup>📌 Chưa rõ, cần thêm thông tin hãy trao đổi với @tolaptrinh-issue  </sup>

**Comment by lequocthong29** [comment]
## HD.05
-  ✔️ **Đã tiếp nhận** 
-  👉 **Thực hiện**: Thực hiện các yêu cầu theo luồng công việc này.
-  📆 **Thời gian hoàn thành :**  2024-12-20.

**Comment by gh-dh-bot-00** [comment]
### 📣📣📣 Prescription.exe v.3.24.1219.0 <sub><sup><sup>[⬇️OneDrive](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412190-OneDrive.json) [⬇️GoogleStorage](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412190-GoogleStorage.json) [⬇️NasDHSolutions](https://code-dh-hospital.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2FdirectTo%2FPrescriptionexe%2F32412190-NasDHSolutions.json)</sup></sup></sub>

## Nội dung thay đổi


- 🐛: Lỗi - Nhập viện đối tượng thu phí

![](https://i.imgur.com/hOyo9Hi.gif)

- ☑: https://github.com/dhhiswork/Loi/issues/98
<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/code-dh-hospital/Prescription.exe) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>
